# Importação de Libs

In [1]:
import os
import pandas as pd

# Importando Kaggle e Carregando Dataset

In [2]:
import kagglehub
# Download latest version
path = kagglehub.dataset_download("eduardopalmieri/nba-player-stats-season-2425")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\vinic\.cache\kagglehub\datasets\eduardopalmieri\nba-player-stats-season-2425\versions\37

In [3]:
df = pd.read_csv(os.path.join(path, "database_24_25.csv"))

# Descrição do DataSet

| Nome       | Descrição                                        | Tipo do Dado                 |
| ---------- | ------------------------------------------------ | ---------------------------- |
| **Player** | Nome do jogador                                  | `string`                     |
| **Tm**     | Sigla do time do jogador                         | `string`                     |
| **Opp**    | Sigla do time adversário                         | `string`                     |
| **Res**    | Resultado do jogo (Win/Loss)                     | `string`                     |
| **MP**     | Minutos jogados (ex: 23.5 = 23min30s)            | `float64`                    |
| **FG**     | Cestas de quadra convertidas                     | `int64`                      |
| **FGA**    | Tentativas de arremessos de quadra               | `int64`                      |
| **FG%**    | Percentual de acerto nos arremessos de quadra    | `float64`                    |
| **3P**     | Cestas de 3 pontos convertidas                   | `int64`                      |
| **3PA**    | Tentativas de 3 pontos                           | `int64`                      |
| **3P%**    | Percentual de acerto de 3 pontos                 | `float64`                    |
| **FT**     | Lances livres convertidos                        | `int64`                      |
| **FTA**    | Tentativas de lances livres                      | `int64`                      |
| **FT%**    | Percentual de acerto de lances livres            | `float64`                    |
| **ORB**    | Rebotes ofensivos                                | `int64`                      |
| **DRB**    | Rebotes defensivos                               | `int64`                      |
| **TRB**    | Total de rebotes                                 | `int64`                      |
| **AST**    | Assistências                                     | `int64`                      |
| **STL**    | Roubos de bola                                   | `int64`                      |
| **BLK**    | Tocos (bloqueios)                                | `int64`                      |
| **TOV**    | Turnovers (perdas de bola)                       | `int64`                      |
| **PF**     | Faltas pessoais                                  | `int64`                      |
| **PTS**    | Pontos totais no jogo                            | `int64`                      |
| **GmSc**   | Game Score (métrica de desempenho geral no jogo) | `float64`                    |
| **Date**   | Data do jogo (formato YYYY-MM-DD)                | `datetime64`   |

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  16512 non-null  object
 1   Tm      16512 non-null  object
 2   Opp     16512 non-null  object
 3   Res     16512 non-null  object
 4   MP      16512 non-null  float64
 5   FG      16512 non-null  int64
 6   FGA     16512 non-null  int64
 7   FG%     16512 non-null  float64
 8   3P      16512 non-null  int64
 9   3PA     16512 non-null  int64
 10  3P%     16512 non-null  float64
 11  FT      16512 non-null  int64
 12  FTA     16512 non-null  int64
 13  FT%     16512 non-null  float64
 14  ORB     16512 non-null  int64
 15  DRB     16512 non-null  int64
 16  TRB     16512 non-null  int64
 17  AST     16512 non-null  int64
 18  STL     16512 non-null  int64
 19  BLK     16512 non-null  int64
 20  TOV     16512 non-null  int64
 21  PF      16512 non-null  int64
 22  PTS     16512 non-null  int64
 23  GmSc    16512 non-null  float64
 24  Data    16512 non-null  object
dtypes: float64(5), int64(15), object(5)
memory usage: 3.1+ MB

In [5]:
#DIMENSÕES E ESTRUTURA
df.shape

(16512, 25)

# Estatísticas Descritivas

In [6]:
print("\n 3. ESTATÍSTICAS DESCRITIVAS (NUMÉRICAS)")
print("="*77)

desc = df.describe().T.round(2)

print(desc)

 3. ESTATÍSTICAS DESCRITIVAS (NUMÉRICAS)
=============================================================================
        count   mean    std  min    25%    50%    75%    max
MP    16512.0  22.41  10.90  0.0  14.43  23.43  31.32  50.48
FG    16512.0   3.85   3.26  0.0   1.00   3.00   6.00  22.00
FGA   16512.0   8.27   6.07  0.0   4.00   7.00  12.00  38.00
FG%   16512.0   0.43   0.25  0.0   0.29   0.44   0.57   1.00
3P    16512.0   1.25   1.52  0.0   0.00   1.00   2.00  10.00
3PA   16512.0   3.48   3.15  0.0   1.00   3.00   5.00  20.00
3P%   16512.0   0.26   0.29  0.0   0.00   0.25   0.50   1.00
FT    16512.0   1.57   2.23  0.0   0.00   1.00   2.00  18.00
FTA   16512.0   2.02   2.69  0.0   0.00   1.00   3.00  26.00
FT%   16512.0   0.42   0.44  0.0   0.00   0.33   1.00   1.00
ORB   16512.0   1.03   1.37  0.0   0.00   1.00   2.00  12.00
DRB   16512.0   3.07   2.72  0.0   1.00   2.00   4.00  23.00
TRB   16512.0   4.10   3.48  0.0   2.00   3.00   6.00  28.00
AST   16512.0   2.45   2.61  0.0   1.00   2.00   4.00  22.00
STL   16512.0   0.77   0.99  0.0   0.00   0.00   1.00   8.00
BLK   16512.0   0.47   0.83  0.0   0.00   0.00   1.00  10.00
TOV   16512.0   1.27   1.43  0.0   0.00   1.00   2.00  11.00
PF    16512.0   1.75   1.44  0.0   1.00   2.00   3.00   6.00
PTS   16512.0  10.52   8.83  0.0   3.00   9.00  16.00  60.00
GmSc  16512.0   8.58   7.82 -7.6   2.40   7.10  13.30  54.20

In [7]:
print("5. ANÁLISE DE DUPLICATAS")
print("="*60)

duplicatas = df.duplicated().sum()
total = len(df)

print(f"Total de registros: {total}")
print(f"Total de duplicatas: {duplicatas}")

if duplicatas > 0:
    print("\n🔍 Exemplos de duplicatas:")
    print(df[df.duplicated(keep=False)].head())

5. ANÁLISE DE DUPLICATAS
============================================================
Total de registros: 16512
Total de duplicatas: 0

In [8]:
#Números Nulos
print("5. ANÁLISE DE NULOS")
print("="*60)
df.isnull().sum()

5. ANÁLISE DE NULOS
============================================================

Player    0
Tm        0
Opp       0
Res       0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
GmSc      0
Data      0
dtype: int64

# Análises Jogador

In [9]:
#Os Jogadores que mais pontuaram
df_top50 = df.sort_values(by="PTS", ascending=False).head(10)
df_top50

,Player,Tm,Opp,Res,MP,FG,FGA,FG%,3P,3PA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,Data
3864,De'Aaron Fox,SAC,MIN,L,44.48,22,35,0.629,6,10,...,1,3,7,3,1,6,3,60,47.0,2024-11-15
3619,Giannis Antetokounmpo,MIL,DET,W,43.63,21,34,0.618,1,2,...,11,14,7,2,3,3,1,59,54.2,2024-11-13
7368,Nikola Jokić,DEN,WAS,L,38.65,22,38,0.579,3,5,...,9,16,8,1,0,5,5,56,43.8,2024-12-07
9863,Jalen Brunson,NYK,WAS,W,44.00,18,31,0.581,3,11,...,3,3,9,0,0,3,1,55,43.9,2024-12-28
13752,Shai Gilgeous-Alexander,OKC,UTA,W,37.47,17,35,0.486,3,10,...,5,8,5,3,2,3,3,54,43.2,2025-01-22
10955,Anthony Edwards,MIN,DET,L,44.45,16,31,0.516,10,15,...,5,6,2,0,0,6,4,53,33.3,2025-01-04
14849,Shai Gilgeous-Alexander,OKC,GSW,L,39.10,16,29,0.552,2,6,...,3,3,4,1,0,3,4,52,37.0,2025-01-29
16002,Shai Gilgeous-Alexander,OKC,PHO,W,34.25,18,29,0.621,3,7,...,6,8,5,2,1,1,3,50,43.7,2025-02-05
5183,LaMelo Ball,CHO,MIL,L,39.68,17,38,0.447,6,17,...,5,5,10,1,0,4,3,50,33.3,2024-11-23
3620,Victor Wembanyama,SAS,WAS,W,32.45,18,29,0.621,8,16,...,5,6,2,1,3,1,3,50,40.2,2024-11-13

In [10]:
#Jogadores que tem maior media de desempenho geral
df_top50.sort_values(by="GmSc", ascending=False).head(10)

,Player,Tm,Opp,Res,MP,FG,FGA,FG%,3P,3PA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,Data
3619,Giannis Antetokounmpo,MIL,DET,W,43.63,21,34,0.618,1,2,...,11,14,7,2,3,3,1,59,54.2,2024-11-13
3864,De'Aaron Fox,SAC,MIN,L,44.48,22,35,0.629,6,10,...,1,3,7,3,1,6,3,60,47.0,2024-11-15
9863,Jalen Brunson,NYK,WAS,W,44.00,18,31,0.581,3,11,...,3,3,9,0,0,3,1,55,43.9,2024-12-28
7368,Nikola Jokić,DEN,WAS,L,38.65,22,38,0.579,3,5,...,9,16,8,1,0,5,5,56,43.8,2024-12-07
16002,Shai Gilgeous-Alexander,OKC,PHO,W,34.25,18,29,0.621,3,7,...,6,8,5,2,1,1,3,50,43.7,2025-02-05
13752,Shai Gilgeous-Alexander,OKC,UTA,W,37.47,17,35,0.486,3,10,...,5,8,5,3,2,3,3,54,43.2,2025-01-22
3620,Victor Wembanyama,SAS,WAS,W,32.45,18,29,0.621,8,16,...,5,6,2,1,3,1,3,50,40.2,2024-11-13
14849,Shai Gilgeous-Alexander,OKC,GSW,L,39.10,16,29,0.552,2,6,...,3,3,4,1,0,3,4,52,37.0,2025-01-29
10955,Anthony Edwards,MIN,DET,L,44.45,16,31,0.516,10,15,...,5,6,2,0,0,6,4,53,33.3,2025-01-04
5183,LaMelo Ball,CHO,MIL,L,39.68,17,38,0.447,6,17,...,5,5,10,1,0,4,3,50,33.3,2024-11-23

In [11]:
#Criando uma nova coluna de impacto geral
df_top50["Impacto"] = df_top50["PTS"] + df_top50["AST"] + df_top50["TRB"]
df_top50.sort_values(by="Impacto", ascending=False).head(10)

,Player,Tm,Opp,Res,MP,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,Data,Impacto
3619,Giannis Antetokounmpo,MIL,DET,W,43.63,21,34,0.618,1,2,...,14,7,2,3,3,1,59,54.2,2024-11-13,80
7368,Nikola Jokić,DEN,WAS,L,38.65,22,38,0.579,3,5,...,16,8,1,0,5,5,56,43.8,2024-12-07,80
3864,De'Aaron Fox,SAC,MIN,L,44.48,22,35,0.629,6,10,...,3,7,3,1,6,3,60,47.0,2024-11-15,70
9863,Jalen Brunson,NYK,WAS,W,44.00,18,31,0.581,3,11,...,3,9,0,0,3,1,55,43.9,2024-12-28,67
13752,Shai Gilgeous-Alexander,OKC,UTA,W,37.47,17,35,0.486,3,10,...,8,5,3,2,3,3,54,43.2,2025-01-22,67
5183,LaMelo Ball,CHO,MIL,L,39.68,17,38,0.447,6,17,...,5,10,1,0,4,3,50,33.3,2024-11-23,65
16002,Shai Gilgeous-Alexander,OKC,PHO,W,34.25,18,29,0.621,3,7,...,8,5,2,1,1,3,50,43.7,2025-02-05,63
10955,Anthony Edwards,MIN,DET,L,44.45,16,31,0.516,10,15,...,6,2,0,0,6,4,53,33.3,2025-01-04,61
14849,Shai Gilgeous-Alexander,OKC,GSW,L,39.10,16,29,0.552,2,6,...,3,4,1,0,3,4,52,37.0,2025-01-29,59
3620,Victor Wembanyama,SAS,WAS,W,32.45,18,29,0.621,8,16,...,6,2,1,3,1,3,50,40.2,2024-11-13,58